socialnetworkproject/loginapp/urls.py
from django.urls import path
from . import views


app_name = 'loginapp'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('signup', views.signup, name='signup'),
    path('logout', views.logout, name='logout'),
    path('reset-password', views.reset_password, name='reset-password'),
    path('profile', views.profile, name='profile'),
]

socialnetworkproject/socialnetworkapp/urls.py
from django.urls import path
from . import views
from .views import  PostList, PostDetail


app_name = 'socialnetworkapp'

urlpatterns = [
    path('index', views.index, name='index'),
    path('groups', views.groups, name='groups'),
    path('join_group/<int:pk>', views.join_group, name='join_group'),
    path('leave_group/<int:pk>', views.leave_group, name='leave_group'),
    path('<int:pk>/', PostDetail.as_view()),
    path('api/v1/', PostList.as_view()),
]

socialnetworkproject/socialnetworkproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/', include('loginapp.urls', namespace='loginapp')),
    path('', include('socialnetworkapp.urls', namespace='socialnetworkapp')),
    path('api/v1/', include('socialnetworkapp.urls')),
    path('admin/', admin.site.urls),
]

#if we are in a debug mode we want to add thid static pattern
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

socialnetworkproject/loginapp/models.py
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpeg', upload_to='profile_pics')

    def __str__(self):
        return f'{self.user.username} Profile'

socialnetworkproject/socialnetworkapp/models.py
from django.db import models
from django.contrib.auth.models import User


class AppGroup(models.Model):
    # Meta
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='owners')
    users = models.ManyToManyField(User)
    # Data
    name = models.CharField(max_length=200)
    description = models.TextField()

    def __str__(self):
        return self.name


class Post(models.Model):
    # Meta
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    group = models.ForeignKey(AppGroup, on_delete=models.CASCADE)
    last_updated = models.DateTimeField(auto_now=True)
    # Data
    text = models.TextField()

    def __str__(self):
        return self.text[:25]

socialnetworkproject/loginapp/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login as dj_login, logout as dj_logout
import sys
sys.path.append('/your/dir/to/tensorflow/models') # point to your tensorflow dir
sys.path.append('/your/dir/to/tensorflow/models/slim') # point ot your slim dir
from celery import Celery
import yagmail


def login(request):
    context = {}
    if request.method == 'POST':
        user = authenticate(request,
                            username = request.POST['user'],
                            password = request.POST['password'])

        if user:
            dj_login(request, user)
            return HttpResponseRedirect(reverse('socialnetworkapp:index'))
        else:
            context['error'] = 'Username or password is wrong.'

    return render(request, 'loginapp/login.html', context)


def logout(request):
    dj_logout(request)
    return HttpResponseRedirect(reverse('loginapp:login'))


def signup(request):
    if User.is_authenticated:
        dj_logout(request)
    context = {}

    if request.method == 'POST':
        if not request.POST['password'] == request.POST['repeatpassword']:
            context['error'] = 'Passwords do not match.'
            return render(request, 'loginapp/signup.html', context)

        if len(User.objects.filter(username = request.POST['user'])) > 0:
            context['error'] = 'Username already exists.'
            return render(request, 'loginapp/signup.html', context)

        if len(User.objects.filter(email = request.POST['email'])) > 0:
            context['error'] = 'Email already exists.'
            return render(request, 'loginapp/signup.html', context)

        user = User.objects.create_user(request.POST['user'], password = request.POST['password'])
        user.save()
        dj_login(request, user)

        app = Celery()
        app.config_from_object('celeryconfig')

        receiver = "email@gmail.com"
        body = "Congratulations, you are now a part of Social Network. Your life is officially over"

        yag = yagmail.SMTP("email@gmail.com")
        yag.send(
            to=receiver,
            subject="Signup confirmation for Social Network",
            contents=body
        )
        return HttpResponseRedirect(reverse('loginapp:login'))

    return render(request, 'loginapp/signup.html')


def reset_password(request):
    context = {}

    if request.method == 'POST':
        users = User.objects.filter(username = request.POST['user'])

        if users:
            user = users[0]
            new_password = random_string()
            user.set_password(new_password)
            user.save()
            print(f'**** User {user} change password to {new_password}')
            return HttpResponseRedirect(reverse('loginapp:login'))
        else:
            context['error'] = 'Username does not exist! Try again!'

    return render(request, 'loginapp/reset-password.html', context)

@login_required
def profile(request):
    return render(request, 'loginapp/profile.html')

socialnetworkproject/socialnetworkapp/views.py
from django.shortcuts import render, reverse
from django.http import HttpResponseRedirect, HttpResponseBadRequest
from django.contrib.auth.models import User
from . import models
from rest_framework import generics
from .models import Post
from .serializers import PostSerializer

def index(request):

    user = User.objects.filter(pk=1)[0]

    if request.method == 'GET':
        user_groups = models.AppGroup.objects.filter(users__username__contains=user.username)
        print(user, user_groups)
        posts = models.Post.objects.filter(group__in=user_groups).order_by('-created')[:10]

        context = {
            'user': user,
            'posts': posts,
            'user_groups': user_groups,
        }

        return render(request, 'socialnetworkapp/index.html', context=context)

    if request.method == 'POST':
        post = models.Post()
        post.text = request.POST['text']
        post.group = models.AppGroup.objects.get(pk=request.POST['group'])
        post.user = user
        post.save()

        return HttpResponseRedirect(reverse('socialnetworkapp:index'))

    return HttpResponseBadRequest()

def groups(request):

    user = User.objects.filter(pk=1)[0]
    if request.method == 'GET':
        user_groups = models.AppGroup.objects.filter(users__username__contains=user.username)
        not_user_groups = models.AppGroup.objects.exclude(users__username__contains=user.username)

        context = {
            'user_groups': user_groups,
            'not_user_groups': not_user_groups,
            'user': user,
        }

        return render(request, 'socialnetworkapp/groups.html', context=context)

    if request.method == 'POST':
        group = models.AppGroup()
        group.name = request.POST['name']
        group.description = request.POST['description']
        group.owner = user
        group.save()
        group.users.add(user)
        group.save()

        return HttpResponseRedirect(reverse('socialnetworkapp:groups'))

    return HttpResponseBadRequest()


def join_group(request, pk):

    user = User.objects.filter(pk=1)[0]
    group = models.AppGroup.objects.get(pk=pk)
    group.users.add(user)
    group.save()

    return HttpResponseRedirect(reverse('socialnetworkapp:groups'))


def leave_group(request, pk):

    user = User.objects.filter(pk=1)[0]
    group = models.AppGroup.objects.get(pk=pk)
    group.users.remove(user)
    group.save()

    return HttpResponseRedirect(reverse('socialnetworkapp:groups'))

class PostList(generics.ListCreateAPIView):

    queryset =  Post.objects.all()
    serializer_class = PostSerializer

class PostDetail(generics.RetrieveUpdateDestroyAPIView):

    queryset = Post.objects.all()
    serializer_class = PostSerializer

socialnetworkproject/loginapp/templates/loginapp/login.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/docs/4.1/assets/img/favicons/favicon.ico">

    <title>Log in</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.1/examples/sign-in/">

    <!-- Bootstrap core CSS -->
<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <style>
              html,
        body {
          height: 100%;
        }

        body {
          display: -ms-flexbox;
          display: flex;
          -ms-flex-align: center;
          align-items: center;
          padding-top: 40px;
          padding-bottom: 40px;
          background-color: lightsteelblue;
        }

        .form-login {
          width: 100%;
          max-width: 330px;
          padding: 15px;
          margin: auto;
        }

        .form-login .form-control {
          position: relative;
          box-sizing: border-box;
          height: auto;
          padding: 10px;
          font-size: 16px;
        }
        .form-login .form-control:focus {
          z-index: 2;
        }
        .form-login input[type="email"] {
          margin-bottom: -1px;
          border-bottom-right-radius: 0;
          border-bottom-left-radius: 0;
        }
        .form-login input[type="password"] {
          margin-bottom: 10px;
          border-top-left-radius: 0;
          border-top-right-radius: 0;
        }


    </style>
  </head>

  <body class="text-center">
      <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="{% url 'socialnetworkapp:index' %}">Home</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{% url 'loginapp:login' %}">Login</a>
              <a class="nav-item nav-link" href="{% url 'loginapp:signup' %}">Signup</a>
              <a class="nav-item nav-link" href="{% url 'loginapp:profile' %}">My profile</a>
              <a class="nav-item nav-link" href="{% url 'socialnetworkapp:groups' %}">My groups</a>
              <a class="nav-item nav-link" href="{% url 'loginapp:logout' %}">Log out</a>
            </div>
           </div>
        </div>
      </nav>
    </header>

    <form class="form-login" action="." method="POST">
      {% csrf_token %}
      <p>Hello {{user}}! You are now logged in</p>
      <h1 class="h3 mb-3 font-weight-normal">Please log in</h1>
      <label for="user" class="sr-only">Username</label>
      <br />
      <input type="text" id="user" name="user" class="form-control" placeholder="Username" required autofocus>
      <br />
      <label for="password" class="sr-only">Password</label>
      <br />
      <input type="password" id="password" name="password" class="form-control" placeholder="Password" required>
      <br />
      <button class="btn btn-lg btn-primary btn-block" value="Submit" type="submit">Log in</button>
      <br />
      {% if error %}
        <p class="error">{{ error }}</p>
    {% endif  %}
    <hr>
    <a href="{% url 'loginapp:signup' %}">Sign up</a>
      <br>
      <a href="{% url 'loginapp:reset-password' %}">Reset your password</a>
      <p class="mt-5 mb-3 text-muted">&copy; 2019</p>
    </form>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js" integrity="sha384-6khuMg9gaYr5AxOqhkVIODVIvm9ynTT5J4V1cfthmT+emCG6yVmEZsRHdxlotUnm" crossorigin="anonymous"></script>
  </body>
</html>

socialnetworkproject/loginapp/templates/loginapp/profile.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/docs/4.1/assets/img/favicons/favicon.ico">

    <title>User Profile</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.1/examples/sign-in/">

    <!-- Bootstrap core CSS -->
<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
{% load static %}
    <style>
              html,
        body {
          height: 100%;
        }

        body {
          display: -ms-flexbox;
          display: flex;
          -ms-flex-align: center;
          align-items: center;
          padding-top: 40px;
          padding-bottom: 40px;
          background-color: lightsteelblue;
        }

        .profile {
          width: 100%;
          max-width: 330px;
          padding: 15px;
          margin: auto;
           position: relative;
          box-sizing: border-box;
          height: auto;
        }
    </style>
  </head>

  <body class="text-center">
      <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="{% url 'socialnetworkapp:index' %}">Home</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{% url 'loginapp:login' %}">Login</a>
              <a class="nav-item nav-link" href="{% url 'loginapp:signup' %}">Signup</a>
              <a class="nav-item nav-link" href="{% url 'loginapp:profile' %}">My profile</a>
              <a class="nav-item nav-link" href="{% url 'loginapp:logout' %}">Log out</a>
            </div>
           </div>
        </div>
      </nav>
    </header>
    {% block content %}
    <div class="content-section profile">
      <div class="media">
        <img class="rounded-circle account-img" src="{{ user.profile.image.url }}">
        <div class="media-body">
          <h2 class="account-heading">{{ user.username }}</h2>
          <p class="text-secondary">{{ user.email }}</p>
        </div>
      </div>
      <!--  <form class="form-login" action="." method="POST">
      {% csrf_token %}
      <p>Hello {{user}}! You are now logged in</p>
      <h1 class="h3 mb-3 font-weight-normal">Please log in</h1>
      <label for="user" class="sr-only">Username</label>
      <br />
      <input type="text" id="user" name="user" class="form-control" placeholder="Username" required autofocus>
      <br />
      <label for="password" class="sr-only">Password</label>
      <br />
      <input type="password" id="password" name="password" class="form-control" placeholder="Password" required>
      <br />
      <button class="btn btn-lg btn-primary btn-block" value="Submit" type="submit">Log in</button>
      <br />
      {% if error %}
        <p class="error">{{ error }}</p>
    {% endif  %}

      <p class="mt-5 mb-3 text-muted">&copy; 2019</p>
    </form>-->
    </div>
{% endblock content %}

  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js" integrity="sha384-6khuMg9gaYr5AxOqhkVIODVIvm9ynTT5J4V1cfthmT+emCG6yVmEZsRHdxlotUnm" crossorigin="anonymous"></script>
  </body>
</html>

socialnetworkproject/loginapp/templates/loginapp/reset-password.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/docs/4.1/assets/img/favicons/favicon.ico">

    <title>Reset password</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.1/examples/sign-in/">

    <!-- Bootstrap core CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <style>
                  html,
            body {
              height: 100%;
            }

            body {
              display: -ms-flexbox;
              display: flex;
              -ms-flex-align: center;
              align-items: center;
              padding-top: 40px;
              padding-bottom: 40px;
              background-color: lightsteelblue;
            }

            .form-reset {
              width: 100%;
              max-width: 330px;
              padding: 15px;
              margin: auto;
            }

            .form-reset .form-control {
              position: relative;
              box-sizing: border-box;
              height: auto;
              padding: 10px;
              font-size: 16px;
            }
            .form-reset .form-control:focus {
              z-index: 2;
            }
            .form-reset input[type="email"] {
              margin-bottom: -1px;
              border-bottom-right-radius: 0;
              border-bottom-left-radius: 0;
            }
            .form-reset input[type="password"] {
              margin-bottom: 10px;
              border-top-left-radius: 0;
              border-top-right-radius: 0;
            }


        </style>
  </head>

  <body class="text-center">
      <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="{% url 'socialnetworkapp:index' %}">Home</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{% url 'loginapp:login' %}">Login</a>
              <a class="nav-item nav-link" href="{% url 'loginapp:signup' %}">Signup</a>
              <a class="nav-item nav-link" href="{% url 'loginapp:profile' %}">My profile</a>
              <a class="nav-item nav-link" href="{% url 'socialnetworkapp:groups' %}">My groups</a>
              <a class="nav-item nav-link" href="{% url 'loginapp:logout' %}">Log out</a>
            </div>
           </div>
        </div>
      </nav>
    </header>
    <form class="form-reset" action="{% url 'loginapp:reset-password'  %}" method="POST">
      <h1 class="h3 mb-3 font-weight-normal">Reset password for {{user}} </h1>
      {% csrf_token %}
      <label for="user" class="sr-only">Username</label>
      <br />
      <input type="text" id="user" name="user" class="form-control" placeholder="Username" required>
      <br />
        <button class="btn btn-lg btn-primary btn-block" type="submit">Reset</button>
      <br />
      <p class="mt-5 mb-3 text-muted">&copy; 2019</p>
      {% if error %}
        <p class="error">{{ error }}</p>
    {% endif  %}
    </form>

  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js" integrity="sha384-6khuMg9gaYr5AxOqhkVIODVIvm9ynTT5J4V1cfthmT+emCG6yVmEZsRHdxlotUnm" crossorigin="anonymous"></script>
  </body>
</html>

socialnetworkproject/socialnetworkapp/templates/socialnetworkapp/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">


</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="{% url 'socialnetworkapp:index' %}">Home</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{% url 'loginapp:login' %}">Login</a>
              <a class="nav-item nav-link" href="{% url 'loginapp:signup' %}">Signup</a>
              <a class="nav-item nav-link" href="{% url 'loginapp:profile' %}">My profile</a>
              <a class="nav-item nav-link" href="{% url 'loginapp:logout' %}">Log out</a>
            </div>
           </div>
        </div>
      </nav>
    </header>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

socialnetworkproject/socialnetworkapp/templates/socialnetworkapp/groups.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Social network</title>
     <link rel="canonical" href="https://getbootstrap.com/docs/4.1/examples/sign-in/">

    <!-- Bootstrap core CSS -->
<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <style>
              html,
        body {
          height: 100%;
        }

        body {
          display: -ms-flexbox;
          -ms-flex-align: center;
          align-items: center;
          padding-top: 40px;
          padding-bottom: 40px;
          background-color: lightsteelblue;
        }

        .index {
          width: 100%;
          max-width: 330px;
          padding: 15px;
          margin: auto;
           position: relative;
          box-sizing: border-box;
          height: auto;
        }
    </style>
</head>
<body class="text-center">
    <header class="site-header index">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="{% url 'socialnetworkapp:index' %}">Home</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{% url 'loginapp:login' %}">Login</a>
              <a class="nav-item nav-link" href="{% url 'loginapp:signup' %}">Signup</a>
              <a class="nav-item nav-link" href="{% url 'loginapp:profile' %}">My profile</a>
              <a class="nav-item nav-link" href="{% url 'socialnetworkapp:groups' %}">My groups</a>
              <a class="nav-item nav-link" href="{% url 'loginapp:logout' %}">Log out</a>
            </div>
           </div>
        </div>
      </nav>
    </header>
     <h1>Groups</h1>
    <h2>User: {{ user }}</h2>
    <div>
         <h2>Groups you are a member of:</h2>
    {% for group in user_groups  %}
        {% if not group.pk == 1 %}
            <p>
                <a href="{% url 'socialnetworkapp:leave_group' pk=group.pk %}">Leave Group</a>
                - {{ group.name }}
            </p>
        {% endif  %}
    {% endfor %}
    </div>

    <hr>
    <div>
        <h2>Groups you are not a member of:</h2>
        {% for group in not_user_groups %}
            <p><a href="{% url 'socialnetworkapp:join_group' pk=group.pk %}">Join Group</a> - {{ group.name }}</p>
        {% endfor %}
    </div>
    <br>
    <br>
    <div>
         <form action="{% url 'socialnetworkapp:groups' %}" method="POST">
        {% csrf_token %}
        <p><label for="name">Name</label></p>
        <p><input type="text" id="name" name="name"></p>
        <p><label for="description">Description</label></p>
        <p><input type="textarea" id="description" name="description"></p>
        <p><input type="submit" value="OK"></p>
    </form>


    </div>


 <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js" integrity="sha384-6khuMg9gaYr5AxOqhkVIODVIvm9ynTT5J4V1cfthmT+emCG6yVmEZsRHdxlotUnm" crossorigin="anonymous"></script>

</body>
</html>