stonebook/loginapp/urls.py
from django.urls import path
from . import views

app_name = 'loginapp'

urlpatterns = [
    path('', views.index),
]

stonebook/stonebook/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('stonebookapp.urls', namespace='stonebookapp')),
    path('accounts/', include('loginapp.urls', namespace='loginapp')),
]

stonebook/stonebookapp/urls.py
from django.urls import path
from . import views

app_name = 'stonebookapp'

urlpatterns = [
    path('', views.index, name='index'),
    path('groups', views.groups, name='groups'),
    path('join_group/<int:pk>', views.join_group, name='join_group'),
    path('leave_group/<int:pk>', views.leave_group, name='leave_group'),
    path('profile', views.profile, name='profile'),

]

stonebook/loginapp/models.py
from django.db import models
from django.contrib.auth.models import User

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField()

stonebook/stonebookapp/models.py
from django.db import models
from django.contrib.auth.models import User

class AppGroup(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='owners')
    users = models.ManyToManyField(User)
    name = models.CharField(max_length=200)
    description = models.TextField()

    def __str__(self):
        #return the name in the db
        return self.name

class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    group = models.ForeignKey(AppGroup, on_delete=models.CASCADE)
    last_updated = models.DateTimeField(auto_now=True)
    text = models.TextField()

    def __str__(self):
        # return the name in the db
        return self.text[:25]

stonebook/loginapp/views.py
from django.shortcuts import render
from django.http import HttpResponseBadRequest
from django.contrib.auth.models import User
from . import models

def index(request):
    pass

stonebook/stonebookapp/views.py
from django.shortcuts import render, reverse
from django.http import HttpResponseBadRequest, HttpResponseRedirect
from django.contrib.auth.models import User
from . import models

def index(request):
    user = User.objects.filter(pk=1)[0]

    if not request.method == 'GET':
        return HttpResponseBadRequest()

    user_groups = models.AppGroup.objects.filter(users__username__contains=user.username)
    posts = models.Post.objects.filter(group__in=user_groups)

    context = {
        #the user which is logged in not the user which created the post
        'user': user,
        'posts': posts,
    }

    return render(request, 'stonebookapp/index.html', context=context)

    if request.method == 'POST':
        post = models.Post()
        post.text = request.POST['text']
        post.group = request.POST['group']
        post.user = user
        post.save()


def groups(request):
    user = User.objects.filter(pk=1)[0]

    if request.method == 'GET':
        user_groups = models.AppGroup.objects.filter(users__username__contains=user.username)
        not_user_groups = models.AppGroup.objects.exclude(users__username__contains=user.username)

        context = {
            # the user which is logged in not the user which created the post
            'user_groups': user_groups,
            'not_user_groups': not_user_groups,
            'user': user
        }

        return render(request, 'stonebookapp/groups.html', context=context)

    if request.method == 'POST':
        group = models.AppGroup()
        group.name = request.POST['name']
        group.description = request.POST['description']
        group.owner = user
        group.save()
        group.users.add(user)
        group.save()
        return HttpResponseRedirect(reverse('stonebookapp:groups'))

    return  HttpResponseBadRequest()


def join_group(request, pk):
    user = User.objects.filter(pk=1)[0]
    group = models.AppGroup.objects.get(pk=pk)
    group.users.add(user)
    group.save()

    return HttpResponseRedirect(reverse('stonebookapp:groups'))

def leave_group(request, pk):
    user = User.objects.filter(pk=1)[0]
    group = models.AppGroup.objects.get(pk=pk)
    group.users.remove(user)
    group.save()

    return HttpResponseRedirect(reverse('stonebookapp:groups'))


def profile(request):
    pass

stonebook/stonebookapp/templates/stonebookapp/groups.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Groups</title>
</head>
<body>
    <h1>Groups</h1>
    <h2>User: {{ user }}</h2>
    <hr>
    <h2>Groups you are a member of:</h2>
       {% for group in user_groups %}
            {% if not group.pk == 1 %}
               <p>
                   <a href="{% url 'stonebookapp:leave_group' pk=group.pk %}">Leave</a>
                  - {{ group.name }}
               </p>
            {% endif %}
    {% endfor %}
    <hr>
    <h2>Groups you are not a member of:</h2>
       {% for group in not_user_groups %}
             <p>
                 <a href="{% url 'stonebookapp:join_group' pk=group.pk %}">Join</a>

                {{ group.name }}
             </p>

        {% endfor %}

  <hr>
    <form action="{% url 'stonebookapp:groups' %}" method="POST">
        {% csrf_token %}
       <p>
           <label for="name">Name</label>
       </p>
        <p>
            <input type="text" id="name" name="name">       </p>
       </p>
        <p>
           <label for="description">Description</label>
       </p>

        <input type="text" id="description" name="description">       </p>
        <p><input type="submit" value="OK"></p>
    </form>
</body>
</html>

stonebook/stonebookapp/templates/stonebookapp/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Stonebook</title>
</head>
<body>
    <h1>Stonebook</h1>
    <h2>Welcome {{ user }}</h2>
    <hr>
       {% for post in posts %}
        {{ post.text }}
        Created: {{ post.created }}
        Last updated: {{ post.last_updated }}
        By: {{ post.user }}
        <hr>
    {% endfor %}
    <a href="{% url 'stonebookapp:groups' %}">Groups</a>
    <hr>
     <form action="{% url 'stonebookapp:index' %}" method="POST">
        {% csrf_token %}
         <p>
           <label for="group">Choose group</label>
       </p>
         <select name="group" id="group">
             {% for group in user_groups %}
                <option value="{{ group.pk }}">{{ group.name }}</option>
            {% endfor %}

         </select>
         <br>
       <p>
           <label for="text">Text</label>
       </p>
        <p>
            <input type="text" id="text" name="text">       </p>
       </p>
        <p><input type="submit" value="OK"></p>
    </form>
</body>
</html>